[meta]
version = "1.2.0"

[data.remote]
# Pancancer data
"https://zenodo.org/records/10944168/files/expression_matrix.tsv.gz" = "expression_matrix.tsv.gz"
"https://zenodo.org/records/10944168/files/expression_matrix_metadata.tsv.gz" = "expression_matrix_metadata.tsv.gz"
"https://github.com/TCP-Lab/MTP-DB/releases/download/1.25.04/MTPDB_v1.25.04.sqlite.gz" = "MTPDB.sqlite.gz"
"https://toil-xena-hub.s3.us-east-1.amazonaws.com/download/TcgaTargetGtex_rsem_gene_tpm.gz" = "expression_matrix_tpm.tsv.gz"

# ENSG data
"https://zenodo.org/records/14225008/files/ensg_data.csv" = "ensg_data.csv"

# GEO datasets recomputes from Zenodo
"https://zenodo.org/records/11108100/files/GSE121842_expected_count.csv.gz" = "geo/GSE121842.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE121842_metadata.csv.gz" =  "geo/GSE121842.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE159857_expected_count.csv.gz" =  "geo/GSE159857.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE159857_metadata.csv.gz" =  "geo/GSE159857.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE22260_expected_count.csv.gz" =  "geo/GSE22260.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE22260_metadata.csv.gz" =  "geo/GSE22260.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE29580_expected_count.csv.gz" =  "geo/GSE29580.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE29580_metadata.csv.gz" =  "geo/GSE29580.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE60052_expected_count.csv.gz" = "geo/GSE60052.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE60052_metadata.csv.gz" = "geo/GSE60052.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE103001_expected_count.csv.gz" = "geo/GSE103001.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE103001_metadata.csv.gz" = "geo/GSE103001.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE254461_expected_count.csv.gz" = "geo/GSE254461.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE254461_metadata.csv.gz" = "geo/GSE254461.rawmeta.csv.gz"
"https://zenodo.org/records/11183835/files/GSE119224_expected_count.csv.gz" = "geo/GSE119224.counts.csv.gz"
"https://zenodo.org/records/11183835/files/GSE119224_metadata.csv.gz" = "geo/GSE119224.rawmeta.csv.gz"
"https://zenodo.org/records/11183835/files/GSE151352_expected_count.csv.gz" = "geo/GSE151352.counts.csv.gz"
"https://zenodo.org/records/11183835/files/GSE151352_metadata.csv.gz" = "geo/GSE151352.rawmeta.csv.gz"
"https://zenodo.org/records/11183835/files/GSE159260_expected_count.csv.gz" = "geo/GSE159260.counts.csv.gz"
"https://zenodo.org/records/11183835/files/GSE159260_metadata.csv.gz" = "geo/GSE159260.rawmeta.csv.gz"
"https://zenodo.org/records/11183835/files/GSE234927_expected_count.csv.gz" = "geo/GSE234927.counts.csv.gz"
"https://zenodo.org/records/11183835/files/GSE234927_metadata.csv.gz" = "geo/GSE234927.rawmeta.csv.gz"

# Discarded GEO datasets
# These are ready to preprocess, but for some reason or the other they are
# not suitable for DEAs.
# GSE107422 - There are no healthy samples
#"https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE107422&format=file" = "GSE107422_RAW.tar"
# GSE201284 - Healthy samples are of blood, not tissue
#"https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE201284&format=file&file=GSE201284%5Fprocessed%5Fcounts%2Etxt%2Egz" = "GSE201284.tsv.gz"

[data.profiles.test]
"expression_matrix.tsv.gz" = "test_expression_matrix.tsv.gz"

[data.profiles.tissues]
"./config/gene_lists/basic.json" = "./config/gene_lists/tissue_level.json"
