[meta]
version = "1.0.0-rc.1"

[data.remote]
# Pancancer data
"https://zenodo.org/records/10944168/files/expression_matrix.tsv.gz" = "expression_matrix.tsv.gz"
"https://zenodo.org/records/10944168/files/expression_matrix_metadata.tsv.gz" = "expression_matrix_metadata.tsv.gz"
"https://github.com/TCP-Lab/MTP-DB/releases/download/1.24.09/MTPDB.sqlite.gz" = "MTPDB.sqlite.gz"

# ENSG data
"https://gist.githubusercontent.com/MrHedmad/b625febffa6d983399894e1f72d438d7/raw/0652d18fd294b88caf67d4470cf8436263b38089/ensg_data.csv" = "data/in/ensg_data.csv"

# GEO datasets recomputes from Zenodo
"https://zenodo.org/records/10822272/files/GSE121842_expected_count.csv.gz" = "geo/GSE121842.counts.csv.gz"
"https://zenodo.org/records/10822272/files/GSE121842_metadata.csv.gz" =  "geo/GSE121842.rawmeta.csv.gz"
"https://zenodo.org/records/10822272/files/GSE159857_expected_count.csv.gz" =  "geo/GSE159857.counts.csv.gz"
"https://zenodo.org/records/10822272/files/GSE159857_metadata.csv.gz" =  "geo/GSE159857.rawmeta.csv.gz"
"https://zenodo.org/records/10822272/files/GSE22260_expected_count.csv.gz" =  "geo/GSE22260.counts.csv.gz"
"https://zenodo.org/records/10822272/files/GSE22260_metadata.csv.gz" =  "geo/GSE22260.rawmeta.csv.gz"
"https://zenodo.org/records/10822272/files/GSE29580_expected_count.csv.gz" =  "geo/GSE29580.counts.csv.gz"
"https://zenodo.org/records/10822272/files/GSE29580_metadata.csv.gz" =  "geo/GSE29580.rawmeta.csv.gz"
"https://zenodo.org/records/10893923/files/GSE60052_expected_count.csv.gz" = "geo/GSE60052.counts.csv.gz"
"https://zenodo.org/records/10893923/files/GSE60052_metadata.csv.gz" = "geo/GSE60052.rawmeta.csv.gz"

# Discarded GEO datasets
# These are ready to preprocess, but for some reason or the other they are
# not suitable for DEAs.
# GSE107422 - There are no healthy samples
#"https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE107422&format=file" = "GSE107422_RAW.tar"
# GSE201284 - Healthy samples are of blood, not tissue
#"https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE201284&format=file&file=GSE201284%5Fprocessed%5Fcounts%2Etxt%2Egz" = "GSE201284.tsv.gz"

[data.profiles.test]
"expression_matrix.tsv.gz" = "test_expression_matrix.tsv.gz"
