[meta]
version = "1.2.0"

[data.remote]
# Pancancer data
"https://zenodo.org/records/10944168/files/expression_matrix.tsv.gz" = "expression_matrix.tsv.gz"
"https://zenodo.org/records/10944168/files/expression_matrix_metadata.tsv.gz" = "expression_matrix_metadata.tsv.gz"
"https://github.com/TCP-Lab/MTP-DB/releases/download/1.25.24/MTPDB_v1.25.24.sqlite.gz" = "MTPDB.sqlite.gz"
"https://toil-xena-hub.s3.us-east-1.amazonaws.com/download/TcgaTargetGtex_rsem_gene_tpm.gz" = "expression_matrix_tpm.tsv.gz"

# ENSG data
"https://zenodo.org/records/14225008/files/ensg_data.csv" = "ensg_data.csv"

# GEO datasets recomputes from Zenodo
"https://zenodo.org/records/11108100/files/GSE121842_expected_count.csv.gz" = "geo/GSE121842.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE121842_metadata.csv.gz" =  "geo/GSE121842.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE159857_expected_count.csv.gz" =  "geo/GSE159857.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE159857_metadata.csv.gz" =  "geo/GSE159857.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE22260_expected_count.csv.gz" =  "geo/GSE22260.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE22260_metadata.csv.gz" =  "geo/GSE22260.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE29580_expected_count.csv.gz" =  "geo/GSE29580.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE29580_metadata.csv.gz" =  "geo/GSE29580.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE60052_expected_count.csv.gz" = "geo/GSE60052.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE60052_metadata.csv.gz" = "geo/GSE60052.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE103001_expected_count.csv.gz" = "geo/GSE103001.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE103001_metadata.csv.gz" = "geo/GSE103001.rawmeta.csv.gz"
"https://zenodo.org/records/11108100/files/GSE254461_expected_count.csv.gz" = "geo/GSE254461.counts.csv.gz"
"https://zenodo.org/records/11108100/files/GSE254461_metadata.csv.gz" = "geo/GSE254461.rawmeta.csv.gz"
"https://zenodo.org/records/11183835/files/GSE119224_expected_count.csv.gz" = "geo/GSE119224.counts.csv.gz"
"https://zenodo.org/records/11183835/files/GSE119224_metadata.csv.gz" = "geo/GSE119224.rawmeta.csv.gz"
"https://zenodo.org/records/11183835/files/GSE151352_expected_count.csv.gz" = "geo/GSE151352.counts.csv.gz"
"https://zenodo.org/records/11183835/files/GSE151352_metadata.csv.gz" = "geo/GSE151352.rawmeta.csv.gz"
"https://zenodo.org/records/11183835/files/GSE159260_expected_count.csv.gz" = "geo/GSE159260.counts.csv.gz"
"https://zenodo.org/records/11183835/files/GSE159260_metadata.csv.gz" = "geo/GSE159260.rawmeta.csv.gz"
"https://zenodo.org/records/11183835/files/GSE234927_expected_count.csv.gz" = "geo/GSE234927.counts.csv.gz"
"https://zenodo.org/records/11183835/files/GSE234927_metadata.csv.gz" = "geo/GSE234927.rawmeta.csv.gz"

# Discarded GEO datasets
# These are ready to preprocess, but for some reason or the other they are
# not suitable for DEAs.
# GSE107422 - There are no healthy samples
#"https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE107422&format=file" = "GSE107422_RAW.tar"
# GSE201284 - Healthy samples are of blood, not tissue
#"https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE201284&format=file&file=GSE201284%5Fprocessed%5Fcounts%2Etxt%2Egz" = "GSE201284.tsv.gz"

# Proteomics and transcriptomics
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/BRCA/BRCA_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt" = "proteomics/BRCA_tumor_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/BRCA/BRCA_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt" = "proteomics/BRCA_tumor_proteomics.tsv"
#"" = "proteomics/BRCA_normal_RSEM.tsv"
#"" = "proteomics/BRCA_normal_proteomics.tsv"

"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/CCRCC/CCRCC_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt" = "proteomics/CCRCC_tumor_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/CCRCC/CCRCC_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt" = "proteomics/CCRCC_tumor_proteomics.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/CCRCC/CCRCC_RNAseq_gene_RSEM_coding_UQ_1500_log2_Normal.txt" = "proteomics/CCRCC_normal_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/CCRCC/CCRCC_proteomics_gene_abundance_log2_reference_intensity_normalized_Normal.txt" = "proteomics/CCRCC_normal_proteomics.tsv"

"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/COAD/COAD_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt" = "proteomics/COAD_tumor_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/COAD/COAD_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt" = "proteomics/COAD_tumor_proteomics.tsv"
#"" = "proteomics/COAD_normal_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/COAD/COAD_proteomics_gene_abundance_log2_reference_intensity_normalized_Normal.txt" = "proteomics/COAD_normal_proteomics.tsv"

"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/GBM/GBM_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt" = "proteomics/GBM_tumor_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/GBM/GBM_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt" = "proteomics/GBM_tumor_proteomics.tsv"
#"" = "proteomics/GBM_normal_RSEM.tsv"
#"" = "proteomics/GBM_normal_proteomics.tsv"

"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/HNSCC/HNSCC_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt" = "proteomics/HNSCC_tumor_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/HNSCC/HNSCC_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt" = "proteomics/HNSCC_tumor_proteomics.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/HNSCC/HNSCC_RNAseq_gene_RSEM_coding_UQ_1500_log2_Normal.txt" = "proteomics/HNSCC_normal_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/HNSCC/HNSCC_proteomics_gene_abundance_log2_reference_intensity_normalized_Normal.txt" = "proteomics/HNSCC_normal_proteomics.tsv"

"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/LSCC/LSCC_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt" = "proteomics/LSCC_tumor_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/LSCC/LSCC_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt" = "proteomics/LSCC_tumor_proteomics.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/LSCC/LSCC_RNAseq_gene_RSEM_coding_UQ_1500_log2_Normal.txt" = "proteomics/LSCC_normal_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/LSCC/LSCC_proteomics_gene_abundance_log2_reference_intensity_normalized_Normal.txt" = "proteomics/LSCC_normal_proteomics.tsv"

"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/LUAD/LUAD_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt" = "proteomics/LUAD_tumor_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/LUAD/LUAD_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt" = "proteomics/LUAD_tumor_proteomics.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/LUAD/LUAD_RNAseq_gene_RSEM_coding_UQ_1500_log2_Normal.txt" = "proteomics/LUAD_normal_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/LUAD/LUAD_proteomics_gene_abundance_log2_reference_intensity_normalized_Normal.txt" = "proteomics/LUAD_normal_proteomics.tsv"

"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/OV/OV_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt" = "proteomics/OV_tumor_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/OV/OV_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt" = "proteomics/OV_tumor_proteomics.tsv"
#"" = "proteomics/OV_normal_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/OV/OV_proteomics_gene_abundance_log2_reference_intensity_normalized_Normal.txt" = "proteomics/OV_normal_proteomics.tsv"

"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/PDAC/PDAC_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt" = "proteomics/PDAC_tumor_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/PDAC/PDAC_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt" = "proteomics/PDAC_tumor_proteomics.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/PDAC/PDAC_RNAseq_gene_RSEM_coding_UQ_1500_log2_Normal.txt" = "proteomics/PDAC_normal_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/PDAC/PDAC_proteomics_gene_abundance_log2_reference_intensity_normalized_Normal.txt" = "proteomics/PDAC_normal_proteomics.tsv"

"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/UCEC/UCEC_RNAseq_gene_RSEM_coding_UQ_1500_log2_Tumor.txt" = "proteomics/UCEC_tumor_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/UCEC/UCEC_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt" = "proteomics/UCEC_tumor_proteomics.tsv"
#"" = "proteomics/UCEC_normal_RSEM.tsv"
"https://cptac-pancancer-data.s3.us-west-2.amazonaws.com/data_freeze_v1.2_reorganized/UCEC/UCEC_proteomics_gene_abundance_log2_reference_intensity_normalized_Normal.txt" = "proteomics/UCEC_normal_proteomics.tsv"

[data.profiles.test]
"expression_matrix.tsv.gz" = "test_expression_matrix.tsv.gz"

[data.profiles.tissues]
"./config/gene_lists/basic.json" = "./config/gene_lists/tissue_level.json"
