[meta]
version = "1.0.0-rc.1"

[data.remote]
# Pancancer data
"https://toil-xena-hub.s3.us-east-1.amazonaws.com/download/TcgaTargetGtex_gene_expected_count.gz" = "expression_matrix.tsv.gz"
"https://toil-xena-hub.s3.us-east-1.amazonaws.com/download/TcgaTargetGTEX_phenotype.txt.gz" = "expression_matrix_metadata.tsv.gz"
"https://github.com/TCP-Lab/MTP-DB/releases/latest/download/MTPDB.sqlite.gz" = "MTPDB.sqlite.gz"

# GEO datasets
"https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE121842&format=file&file=GSE121842%5Fall%2Ecounts%2Eexp%2Etxt%2Egz" = "GSE121842.tsv.gz"
"https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE159857&format=file&file=GSE159857%5FREZ%2EJuly2017%2Ecoding%5Fgenes%2Eqn%2Esubmission%2Exls%2Egz" = "GSE159857.xls.gz"

# Discarded GEO datasets
# These are ready to preprocess, but for some reason or the other they are
# not suitable for DEAs.
# GSE107422 - There are no healthy samples
#"https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE107422&format=file" = "GSE107422_RAW.tar"
# GSE201284 - Healthy samples are of blood, not tissue
#"https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE201284&format=file&file=GSE201284%5Fprocessed%5Fcounts%2Etxt%2Egz" = "GSE201284.tsv.gz"

[data.profiles.test]
"expression_matrix.tsv.gz" = "test_expression_matrix.tsv.gz"
