#!/usr/bin/env python

from pathlib import Path
import pandas as pd
from functools import reduce
import sys
from tqdm import tqdm


def read_n_fuse(one, two, *args, **kwargs):
    if isinstance(one, Path):
        one = pd.read_csv(one)
    if isinstance(two, Path):
        two = pd.read_csv(two)

    return pd.merge(one, two, *args, **kwargs)

def main(args):
    data = reduce(read_n_fuse, tqdm(args.csv, delay = 2))

    data.to_csv(sys.stdout, index=False)

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()

    parser.add_argument("csv", help="Path to CSVs to fuse", nargs="+", type=Path)

    args = parser.parse_args()

    main(args)

