#!/usr/bin/env python
import sys
import pandas as pd
import numpy as np

def eprint(*args, **kwargs):
    print(*args, **kwargs, file=sys.stderr)

def main(input, output):
    eprint("Loading data to log")
    df = pd.read_csv(input)
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    for c in [c for c in df.columns if df[c].dtype in numerics]:
        df[c] = np.log2(df[c] + 1)
    
    eprint(f"Saving a {df.size}-item frame")
    df.to_csv(output, index=False)


if __name__ == "__main__":
    main(sys.stdin, sys.stdout)


